### ISSUE TITLE
Bootstrap REST API

### ISSUE THREAD

**Issue by em0lar** [chaosinventory/chaosinventory#10]
In the call on 2021-01-22 we decided to use REST. We want to use [django-rest-framework](https://www.django-rest-framework.org/) for it.

**Comment by e1mo** [comment]
For a sensible structure I think #6 needs to be merged approved and merged first. And I think an URL Scheme (@clerie wanted to work on that) would also be beneficial.

**Comment by clerie** [comment]
Basically we replicate all models to an endpoint. Big question is now, how deep we want to nest relations in the response and at which point we want to force additional requests.

**Comment by margau** [comment]
Clarification: The REST-API should be bootstrapped

**Comment by margau** [comment]
Feature Branch: https://github.com/chaosinventory/chaosinventory/tree/feature/rest
Feel free to help with this feature!
