### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by e1mo** [chaosinventory/chaosinventory#2]
Use a separate file for configuration so that there is no need to edit the settings.py manually. `.ini` Files seem like a good fit, the python [configparser](https://docs.python.org/3/library/configparser.html) provides an easy interface to those.

**Comment by margau** [comment]
I would honestly prefer an more advanced format like yaml, json etc. - that should give way more flexibility and "cleaner" structure.

**Comment by e1mo** [comment]
I'm not sure if this would be required. When I try to think about cases
where a two-dimmensional configuration wouldn't fit, I can't think of any.

Realistically we would have

* Paths (Basedir, Media-Uploads, ...)
* Database (host, name, user, password, port)
* Base URL / Domain
* Allowed hosts (lists can be easly represented)

If it's not required a yaml or json would be to complex in my opinion,
if I want to quickly change a setting those have to strict syntax
requirements in my opinion.

**Comment by em0lar** [comment]
In the call on 2021-01-22 we decided to use `ini` as format.
