### ISSUE TITLE
Basic Authentication Setup

### ISSUE THREAD

**Issue by margau** [chaosinventory/chaosinventory#27]
Using django.contrib.auth
Add endpoint for token request, returning django standard tokens
Include token type into URL to allow for future support of other tokens (?)

Depends on #10

**Comment by em0lar** [comment]
Do we want to limit authentication to either e-mail address or username (if yes, which of them do we want?) or do we want to support both? (could be problematic, I think then usernames can't contain the @ symbol)

**Comment by adnidor** [comment]
I would prefer to limit to username

**Comment by em0lar** [comment]
I currently have a problem while implementing this feature. In the last meeting (2021-03-12) we talked about it and especially @e1mo (and also @clerie, I think) said that they see it as requirement to have the login page in the backend and not an API endpoint to which credentials (username/password) are sent. 

For me I see three possibilities and I'm unsure if any of them is good or which of them is the best:
1. Redirect from a frontend to the backend and let the user login there. After a successful login, the backend sets a session cookie (life-time would be by default unlimited)
    * This would not work with native apps, for them we need another option (I would prefer the option below)
    * This requires to run the API and frontend on the same domain
2. A frontend uses OAuth2 (Sends the client to the backend to login; client is redirected with a token; frontend gets credentials from the backend with this token)
    * Every frontend needs to have a backend (if you do not want to copy-and-paste a token presented on the login page [backend]).
    * Open Questions: How to handle new apps (one possibility would be an open API endpoint to register new apps, like Mastodon does)
 3. Have an API endpoint to which you can send credentials and get a token in exchange
     * With this SAML, OIDC... (future features) would not work easily
---

For authentication of native clients I currently see only one option (if 3. is not picked) and I think it's good:

* Create an API endpoint to get a apptoken for your account (you need to be logged in)
  * Could also have a qr-code with the token and the api url like pretix does
