### ISSUE TITLE
Fix failing CI in multiple instances

### ISSUE THREAD

**Issue by clerie** [chaosinventory/chaosinventory#29]
- [x] Autogenerated migrations should be excluded from isort (originally #28)
- [x] `Models.py` has some real issues, both with isort and flake8 (originally here, see https://github.com/chaosinventory/chaosinventory/pull/24/checks?check_run_id=1942974825)

(originally posted by @clerie but heavily refactored by @e1mo to unite #28 and #34 in one issue)

**Comment by e1mo** [comment]
From #34 by @margau :

> E.g.:
> https://github.com/chaosinventory/chaosinventory/pull/31/checks?check_run_id=1990138904
> 
> Some stuff in the migration field is seen critically by isort. We should fix this, maybe by ignoring autogenerated code?
