### ISSUE TITLE
Address failing isort CI

### ISSUE THREAD

**Issue by margau** [chaosinventory/chaosinventory#34]
E.g.:
https://github.com/chaosinventory/chaosinventory/pull/31/checks?check_run_id=1990138904

Some stuff in the migration field is seen critically by isort. We should fix this, maybe by ignoring autogenerated code?

**Comment by e1mo** [comment]
Whilst not a 1:1 duplicate it's similar to #29, therefore closing this and uniting there for a clearer overview.
