### ISSUE TITLE
Infinite Recursion on Overlay and Tag models over parent attribute

### ISSUE THREAD

**Issue by em0lar** [chaosinventory/chaosinventory#62]
The model doesn't validate the parent attribute. It's allowed to set the own id as parent in the `Overlay` and `Tag` model.

**Reproduce**

1. Create a `Tag`/`Overlay` model without a parent 
2. Set the parent attribute of the `Tag`/`Overlay` model to the id of itself

**Comment by e1mo** [comment]
I would it as in #49

**Comment by e1mo** [comment]
As mentioned in #65, django doesn't call the `full_clear()` method (which does all the validation) by default. In that PR I proposed forcefully validating all models, how we want to handle this?
