### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by e1mo** [chaosinventory/chaosinventory#7]
Do we want to specify some sort of codings style? [PEP8](https://pep8.org/) seems like a verry reasonable starting-point to me. Using flake8 this could easily become part of a CI.

**Comment by e1mo** [comment]
Should be implemented once #9 is in there

**Comment by em0lar** [comment]
In the call on 2021-01-22 we decided to use PEP8 as coding style. We also decided that we don't want to enforce code style (merging of pull requests is allowed even if not completely PEP8 compliant)

**Comment by e1mo** [comment]
In accordance with #1 and chaosinventory/documentation#12 this should also, once a documentation structure is in place, be documented
