### ISSUE TITLE
Add OIDC authentication method

### ISSUE THREAD

**Issue by em0lar** [chaosinventory/chaosinventory#73]
**Current Situation**
We only allow authentication via static tokens. These tokens should only be used for example for mobile apps and should only be generated by a user who is already logged in.

**Future**
Implement OpenID Connect as main authentication method for users.

This implementation can be limited. At first we need to implement
- Authorization Code Flow
- Authorization Code Flow + PKCE (without client secret at the moment; for backends where it's not possible to store a secret in a safe way)
- Generation of applications via Management Command
  - View Applications in Admin Interface
- Endpoints
  - /authorize
  - /token
  - /userinfo
  - /introspect
  - /revoke
  - .well-known/...

In the further future we could implement:
- Access validation via scopes (#59)
- Maybe implicit flow (even though I don't like it)
- Authorization Code Flow + PKCE with client secret
- and more things I forgot atm.
- Unittests for the complete OIDC flow

@e1mo and me build already a lot of this features. Therefore at this point a big thanks to @e1mo!
Currently I do a refactoring that will take some time. When this is finished, I'll create a WIP pull request with more detailed ToDo's and test cases

**Comment by clerie** [comment]
Obsolte #97
