### ISSUE TITLE
Non-Renewable tokens can create new tokens

### ISSUE THREAD

**Issue by e1mo** [chaosinventory/chaosinventory#79]
By sending a POST to `/api/authentication/token/` even non-renewable tokens can get a new token (more or less renewing itself).

https://github.com/chaosinventory/chaosinventory/blob/e51756ec32b53ecf2b42dba8a094452f283b81e0/src/tests/authentication/test_token.py#L190-L202

**Comment by clerie** [comment]
Obsolete #97
